name: DBT_Project_5
version: 1.0.0
config-version: 2
profile: DBT_Project_5
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  DBT_Project_5:
    +materialized: view
